##################################################
# Wolfinch Screener config
##################################################

strategies:

notifier:
   telegram:
      token: '1757WIsqZH0'
      chat-id: '33e'

ui:
   enabled : true
   port : 8081